### ISSUE TITLE
Background polling throws "System.SystemException: Unable to fetch flag configurationFlag configuration not present in response"

### ISSUE THREAD

**Issue by MarkHesselberth** [Eppo-exp/dot-net-server-sdk#45]
We recently deployed a mobile app that used the Eppo client in server mode, in order to enable automatic hourly polling for new flag configurations:

```dotnet
var eppoClientConfig = new EppoClientConfig (_apiKey, new AssignmentLogger ()) {
	PollingIntervalInMillis = (long)TimeSpan.FromHours (1).TotalMilliseconds,
	PollingJitterInMillis = 0
};

_client = EppoClient.Init (eppoClientConfig);
```

Unfortunately, we saw a small number of app crashes appearing in our logs after this change, with the following stack trace: 

```
System.SystemException: Unable to fetch flag configurationFlag configuration not present in response
  ?, in VersionedResourceResponse<FlagConfigurationResponse> ConfigurationRequester.FetchFlags(string lastConfigVersion)
  ?, in void ConfigurationRequester.LoadConfiguration()
  ?, in void FetchExperimentsTask.Run()
  ?, in void FetchExperimentsTask.<.ctor>b__4_0(?)+(object state) => { }
  ?, in void TimerQueueTimer.s_callCallbackInContext(object state)
  ?, in void TimerQueueTimer.CallCallback(bool)
  ?, in void TimerQueueTimer.Fire(bool)
  ?, in void TimerQueueTimer.System.Threading.IThreadPoolWorkItem.Execute()
  ?, in void ThreadPoolWorkQueue.DispatchItemWithAutoreleasePool(object, Thread)
  ?, in bool ThreadPoolWorkQueue.Dispatch()
  ?, in void WorkerThread.WorkerThreadStart()
  ?, in void Thread.StartCallback()
```

As far as I could tell, this exception can occur whenever the API call to get the new configuration receives a response with no content body and a HTTP response code other than `HttpStatusCode.NotModified` [(link)](https://github.com/Eppo-exp/dot-net-server-sdk/blob/main/dot-net-sdk/http/ConfigurationRequester.cs#L113). I would therefore assume that this happens whenever some kind of error occurs in the API call.

Because this is happening on background worker threads, running this in a mobile app means that the unhandled errors can cause the entire app to crash, as we do not have a way to catch these errors properly. Would it be possible to either add error handling that catches these exceptions, or add some hook for SDK users to attach their own error handlers?

**Comment by typotter** [comment]
fixed in [v3.3.2](https://github.com/Eppo-exp/dot-net-server-sdk/releases/tag/v3.3.2)
